### ISSUE TITLE
could you please tell me which paper dose you code come from?

### ISSUE THREAD

**Issue by biubiupiu44** [abeagomez/CNN_triplet_loss_with_keras#1]
I'm very interested in your code.Could you please tell me more about how to run the code.Your py file too much.I can't read them very clearly.Thank you very much for your help.

**Comment by abeagomez** [comment]
This is the paper: https://www.sciencedirect.com/science/article/pii/S1077314217302011
This project is designed to classify a private dataset. You can use the project as reference if you are building a similar one. The cnn_reidentification.py script contains all the CNN design and all the information needed to replicate the results. You can ignore anything that isn't referenced inside that script.
